### ISSUE TITLE
Connecting ZyAura ZG106

### ISSUE THREAD

**Issue by ptranavicius** [revspace/co2sensor#4]
Hello,

I am trying to connect a similar device to Arduino, however, I see no logic in the hex code I receive: these is no closing statement and no repeatable identifiers.
How can I troubleshoot that?

Sampel hex feed:
49 8 A1 4F F1 2209
41 4 FF F8 22 1279
Send: 6 48 55 4D 49 4 FF
FB C1 22 F 7 49442
41 1 CB FF 5E 459
Send: 6 48 55 4D 49 1 CB
26 0 E0 1F DD 224
7F F5 21 1 31 62753
FB A2 8 21 E7 41480
41 4 5A 1F 9E 1114
Send: 6 48 55 4D 49 4 5A
48 0 FF FE 11 255
24 42 3F FD 9 16959
FF B0 90 9 20 45200

**Comment by bertrik** [comment]
You have to be sure that the protocol is exactly the same.

The current code sees at least the 0x41 byte (recognised as humidity value) and sends a short message.
If I remember correctly, there is also a kind of checksum mechanism, but it's currently not implemented/checked.

**Comment by bertrik** [comment]
I found the specification of the protocol here
http://www.zyaura.com/support/demo/ZG106_FW_001.ExtSpec.pdf

**Comment by ptranavicius** [comment]
Thank you for your comment,
I see this protocol is exactly the same as used in the sketch, however, i do not get the same results:

My 40 bit stream should look like:
Item MSB LSB Sum CR

However, from the sample data stream I have presented in the post above there I find no logic.
Perhaps there is trouble with the code I am using to convert decode hex? https://github.com/ptranavicius/ZG106-Arduino

**Comment by bertrik** [comment]
To be honest, I don't really know at this moment. The code looks OK. Probably there are plenty of things you can improve on my code (e.g. make it non-blocking). I agree we should at least see the CR for example. Can you put the signals on a scope and very the waveforms and the timing against the specification?

Have you also made sure you haven't made some silly simple mistake like swapping the data and clock pin?

**Comment by Votvirak** [comment]
> 
> 
> Hello,
> 
> I am trying to connect a similar device to Arduino, however, I see no logic in the hex code I receive: these is no closing statement and no repeatable identifiers.
> How can I troubleshoot that?
> 
> Sampel hex feed:
> 49 8 A1 4F F1 2209
> 41 4 FF F8 22 1279
> Send: 6 48 55 4D 49 4 FF
> FB C1 22 F 7 49442
> 41 1 CB FF 5E 459
> Send: 6 48 55 4D 49 1 CB
> 26 0 E0 1F DD 224
> 7F F5 21 1 31 62753
> FB A2 8 21 E7 41480
> 41 4 5A 1F 9E 1114
> Send: 6 48 55 4D 49 4 5A
> 48 0 FF FE 11 255
> 24 42 3F FD 9 16959
> FF B0 90 9 20 45200

Hello ptranavicius,
did you find out how to read data from ZG106? I would be verz pleased if you send me the right code.

Thanks

**Comment by ptranavicius** [comment]
Hello,

Yes wrong ground connection ;-)))
